media:
  input: public
  output: /
content:
  - name: pages
    label: Pages
    type: collection
    path: '_pages'
    view:
      fields: [ title, published ]
    fields:
      - name: published
        label: Published
        type: boolean
        default: true
      - name: title
        label: Title
        type: string
      - name: body
        label: body
        type: rich-text