media:
  input: public
  output: /
content:
  - name: pages
    label: Pages
    type: collection
    path: '_pages'
    view:
      fields: [ title, published ]
    fields:
      - name: published
        label: Published
        type: boolean
        default: true
      - name: title
        label: Title
        type: string
      - name: blocks
        label: Page Sections
        type: object
        list: true
        fields:        
          # Hero Block
          - name: hero
            label: Hero Section
            type: object
            fields:
              - name: heading
                label: Heading
                type: string
              - name: subheading
                label: Subheading
                type: text
              - name: background
                label: Background Image
                type: image
              - name: cta
                label: Call to Action
                type: object
                fields:
                  - name: text
                    label: CTA Text
                    type: string
                  - name: link
                    label: CTA Link
                    type: string
          
          # Text Block
          - name: text_block
            label: Text Block
            type: object
            fields:
              - name: title
                label: Title
                type: string
              - name: content
                label: Content
                type: rich-text
          
          # Image Block
          - name: image_block
            label: Image Block
            type: object
            fields:
              - name: image
                label: Image
                type: image
              - name: caption
                label: Caption
                type: string
          
          # Features Grid
          - name: features_grid
            label: Features Grid
            type: object
            fields:
              - name: title
                label: Title
                type: string
              - name: features
                label: Features
                type: object
                list: true
                fields:
                  - name: icon
                    label: Icon
                    type: string
                  - name: title
                    label: Feature Title
                    type: string
                  - name: description
                    label: Description
                    type: text
          
          # Testimonial Block
          - name: testimonial
            label: Testimonial
            type: object
            fields:
              - name: quote
                label: Quote
                type: text
              - name: author
                label: Author
                type: string
              - name: position
                label: Position
                type: string
              - name: avatar
                label: Avatar
                type: image
          
          # Contact Form
          - name: contact_form
            label: Contact Form
            type: object
            fields:
              - name: title
                label: Title
                type: string
              - name: email
                label: Recipient Email
                type: string
              - name: fields
                label: Form Fields
                type: object
                list: true
                fields:
                  - name: label
                    label: Field Label
                    type: string
                  - name: type
                    label: Field Type
                    type: select
                    options: 
                      values: [text, email, textarea, phone]
                  - name: required
                    label: Required
                    type: boolean
                    default: false
      
      # Page-level SEO and Metadata
      - name: seo_title
        label: SEO Title
        type: string
      - name: seo_description
        label: SEO Description
        type: text
      - name: layout
        label: Page Layout
        type: select
        options:
          values: [default, full-width, minimal]