media:
  input: public
  output: /
content:
  - name: pages
    label: Pages
    type: collection
    path: '_pages'
    view:
      fields: [ title, published ]
    fields:
      - name: published
        label: Published
        type: boolean
        default: true
      - name: title
        label: Title
        type: string
      - name: content
        label: Page Content
        type: portable-text
        marks:
          decorators:
            - title
            - strong
            - em
            - underline
            - strike-through
        blocks:
          - name: heading
            type: object
            fields:
              - name: level
                type: number
                default: 2
              - name: text
                type: string
          - name: image
            type: object
            fields:
              - name: src
                type: image
              - name: alt
                type: string
              - name: caption
                type: string
          - name: quote
            type: object
            fields:
              - name: text
                type: text
              - name: author
                type: string
          - name: callout
            type: object
            fields:
              - name: type
                type: select
                options:
                  - info
                  - warning
                  - success
                  - error
              - name: content
                type: text
          - name: code
            type: object
            fields:
              - name: language
                type: string
              - name: code
                type: text
      
      # Page-level metadata
      - name: seo_title
        label: SEO Title
        type: string
      - name: seo_description
        label: SEO Description
        type: text